feat(users): implement GET single user API
tech-university-india/staffing-pipeline-backend pull request #16
Opened 2023-02-10 05:47 UTC by Sukhacoder02

- implemented GET /users/:user_id to get a single user with given ```user_id``` from the db.
![Screenshot 2023-02-10 at 11 02 45 AM](https://user-images.githubusercontent.com/62611006/218009688-dba12748-5cb0-487c-bbc4-a6e387657a01.png)
- added test cases for user.service
- added test cases for user.controller
![Screenshot 2023-02-10 at 10 59 36 AM](https://user-images.githubusercontent.com/62611006/218009859-f7b375b8-7b82-4ab2-a3b5-3a728f25506b.png)

2023-02-10 06:02 UTC, rohini-senthil commented on src/services/user.service.js
> +  getOneUser: async (user_id) => {
Can we rename these functions to `listUsers` and `getUser`

2023-02-10 06:06 UTC, Sukhacoder02 commented on src/services/user.service.js
> +  getOneUser: async (user_id) => {
Sure, working on these.

2023-02-10 06:12 UTC, Sukhacoder02 commented on src/services/user.service.js
> +  getOneUser: async (user_id) => {
Done, waiting for review.

2023-02-10 06:15 UTC, rohini-senthil commented on src/controllers/user.controller.js
>  const getUsers = async (_, res) => {
Can we rename this to `listUsers` as well?

2023-02-10 06:15 UTC, rohini-senthil commented on src/controllers/user.controller.js
> +const getUserById = async (req, res) => {
And rename this to just `getUser`?

2023-02-10 06:16 UTC, Sukhacoder02 commented on src/controllers/user.controller.js
>  const getUsers = async (_, res) => {
So, should I use the same function names for all controllers as well as services?

2023-02-10 06:19 UTC, rohini-senthil commented on src/controllers/user.controller.js
>  const getUsers = async (_, res) => {
In this case, yes.

2023-02-10 06:43 UTC, Sukhacoder02 commented on src/controllers/user.controller.js
>  const getUsers = async (_, res) => {
I'll surely get to that.

2023-02-12 04:43 UTC, rohini-senthil commented on src/routes/user.route.js
> +// router.post('/users', validator(schemas.userSchema, 'body'), postUser);
Why is the create user route commented out?

2023-02-12 04:44 UTC, rohini-senthil commented on src/routes/user.route.js
> +router.get('/users/:user_id', validator(schemas.userIdSchema, 'params'), getUser);
Can you also add auth validation to this?

2023-02-12 08:19 UTC, Sukhacoder02 commented on src/routes/user.route.js
> +router.get('/users/:user_id', validator(schemas.userIdSchema, 'params'), getUser);
Added.

2023-02-12 10:16 UTC, rohini-senthil commented on src/middlewares/schemas.validator.js
> +const userIdSchema = Joi.object({
I think we can directly do 
```
Joi.string().uuid({
  version: ['uuidv4', 'uuidv1'],
});
```
Also, let's move user related validators to `user.validator.js`

2023-02-12 10:25 UTC, rohini-senthil commented on tests/controllers/user.controller.test.js
> +  // describe('deleteUser test', () => {
Why is this commented?

2023-02-12 10:28 UTC, rohini-senthil commented on tests/controllers/user.controller.test.js
> +          image: null,
Can we move common mocks to a `mocks` folder under tests folder. It's starting to crowd the file

2023-02-12 10:28 UTC, rohini-senthil requested changes
Requested changes

2023-02-14 06:01 UTC, rohini-senthil commented on src/utils/HttpError.js
>      this.statusCode = code;
Can we change the file name to httpError?

2023-02-14 06:17 UTC, Sukhacoder02 commented on src/utils/HttpError.js
>      this.statusCode = code;
Done, waiting for review.

2023-02-14 06:18 UTC, Sukhacoder02 commented on src/utils/HttpError.js
>      this.statusCode = code;
Oops, still some imports left to change, will try to do so as soon as possible.
Sorry.

2023-02-14 06:46 UTC, Sukhacoder02 commented on src/utils/HttpError.js
>      this.statusCode = code;
I've renamed all the imports to camelCase and CI tests are successful.
Waiting for merger.

2023-02-14 07:17 UTC, rohini-senthil approved these changes

2023-02-14 07:18 UTC, merged