feat: implement delete project api
tech-university-india/staffing-pipeline-backend pull request #21
Opened 2023-02-10 15:06 UTC by sneh258

Add service and controller for delete project API
Modify engagement model, set engagement_id as primary key
Add test cases for delete project API service and controller

2023-02-12 04:45 UTC, rohini-senthil commented on src/models/engagements.js
> +      engagement_id: {
I think you would need to keep this in camel case

2023-02-12 04:45 UTC, rohini-senthil commented on src/routes/project.route.js
> +projectRouter.get('/:id', authMiddlewares.reqAuthValidator, projectController.deleteProject);
This should be `projectRouter.delete`?

2023-02-12 05:27 UTC, sneh258 commented on src/models/engagements.js
> +      engagement_id: {
Yes will do that

2023-02-12 05:28 UTC, sneh258 commented on src/routes/project.route.js
> +projectRouter.get('/:id', authMiddlewares.reqAuthValidator, projectController.deleteProject);
yes this was a typing error now has been resolved

2023-02-12 07:20 UTC, rohini-senthil commented on src/services/project.service.js
> +    const user_data = await users.findOne({
Can we change `user_data` to camel case

2023-02-12 07:21 UTC, sneh258 commented on src/services/project.service.js
> +    const user_data = await users.findOne({
yes sure

2023-02-12 09:42 UTC, Chetan-MckinseyBEBR reviewed
Added few comments

2023-02-12 09:42 UTC, Chetan-MckinseyBEBR commented on tests/controllers/project.controller.test.js
> +    jest.spyOn(getProjectServices, 'deleteProject').mockResolvedValue('engagement has been deleted');
`getProjectServices` has `deleteProject`? its a confusing when reading. U can name it more generic like `projectService`

2023-02-12 09:42 UTC, Chetan-MckinseyBEBR commented on tests/services/project.service.test.js
> +
remove empty line in objects

2023-02-12 09:51 UTC, sneh258 commented on tests/controllers/project.controller.test.js
> +    jest.spyOn(getProjectServices, 'deleteProject').mockResolvedValue('engagement has been deleted');
yes done

2023-02-12 09:52 UTC, sneh258 commented on tests/services/project.service.test.js
> +
yes I have removed them

2023-02-12 10:01 UTC, Chetan-MckinseyBEBR reviewed
Have singular names. projectController & projectService

2023-02-12 10:01 UTC, Chetan-MckinseyBEBR commented on tests/controllers/project.controller.test.js
Have singular names.  projectController & projectService

2023-02-12 10:05 UTC, sneh258 commented on tests/controllers/project.controller.test.js
yes done

2023-02-12 10:07 UTC, Chetan-MckinseyBEBR approved these changes

2023-02-12 10:13 UTC, rohini-senthil requested changes

2023-02-12 10:13 UTC, rohini-senthil commented on src/services/project.service.js
> +    );
Direct user table/db methods should reside in user.service and should be imported and called here

2023-02-12 10:39 UTC, sneh258 commented on src/services/project.service.js
> +    );
So can we just delete the engagement id for now and once the APIs in the user services are completed we can add the logic there?

2023-02-12 10:40 UTC, sneh258 commented on src/services/project.service.js
> +    );
I can raise a PR for the delete project which will delete the project id only from the engagement table for now. And once everything is completed we can go ahead with the dependent relations

2023-02-12 16:37 UTC, sneh258 commented on src/services/project.service.js
> +    );
yes I have made the changes and pushed it.

2023-02-14 03:18 UTC, rohini-senthil commented on src/controllers/project.controller.js
> +    await projectServices.deleteProject(id);
Can we import it as `projectService` instead?

2023-02-14 03:25 UTC, sneh258 commented on src/controllers/project.controller.js
> +    await projectServices.deleteProject(id);
sure yes

2023-02-14 03:27 UTC, sneh258 commented on src/controllers/project.controller.js
> +    await projectServices.deleteProject(id);
Done

2023-02-14 03:31 UTC, rohini-senthil commented on src/services/project.service.js
> +  await deleteProjectFromUser(userIds, id);
Let's also change the `engagementId` from case study entity as `null`?

2023-02-14 03:37 UTC, rohini-senthil commented on src/services/project.service.js
> +  await deleteProjectFromUser(userIds, id);
Also, can we move the `deleteProjectFromUser` to the controller? – your base db methods should reside in the service files, if there are more than one service that needs to be called – we move it to the controller layer

2023-02-14 03:49 UTC, rohini-senthil commented on src/services/user.service.js
> +  });
This can be refactored into a single query as:

```
const users = await db.users.FindAll({
  where: {
    userId: {
      [Op.or]: userIds,
    }
  }
})
```
Then you can modify the `currentEngagementIds` and `pastEngagementIds` with a forEach loop and update the user inside the loop rather than having a separate function for it again

2023-02-14 17:42 UTC, rohini-senthil commented on src/services/project.service.js
> +const deleteProjectFromEngagement = async id => {
This should be named `deleteProject`

2023-02-14 17:43 UTC, rohini-senthil commented on src/controllers/project.controller.js
> +    const userIds = await projectService.getUsersFromEngagement(id);
Instead of adding a new function, let's reuse `getProject` service method and extract the `userIds` field

2023-02-14 17:45 UTC, rohini-senthil commented on src/services/user.service.js
> +const deleteProjectFromUser = async (userIds, id) => {
lets rename this to `deleteProjectFromUsers` or move the loop on each user outside and leave the name as is (singular)

2023-02-14 17:52 UTC, sneh258 commented on src/services/user.service.js
> +const deleteProjectFromUser = async (userIds, id) => {
I have renamed this

2023-02-14 17:52 UTC, sneh258 commented on src/controllers/project.controller.js
> +    const userIds = await projectService.getUsersFromEngagement(id);
yes, done

2023-02-14 17:52 UTC, sneh258 commented on src/services/project.service.js
> +const deleteProjectFromEngagement = async id => {
yes done

2023-02-14 18:00 UTC, rohini-senthil commented on src/services/user.service.js
> +  const user = await userIds.map(async uid => {
Can we rename this variable to `updateUsers`

2023-02-14 18:00 UTC, rohini-senthil commented on src/services/user.service.js
> +  const getUserData = await Promise.all(user);
Let's rename this variable to `users`

2023-02-14 18:01 UTC, rohini-senthil commented on src/services/user.service.js
> +  getUserData.map(async userElement => {
Let's rename userElement to user

2023-02-14 18:14 UTC, sneh258 commented on src/services/user.service.js
> +  getUserData.map(async userElement => {
done

2023-02-14 18:14 UTC, sneh258 commented on src/services/user.service.js
> +  const getUserData = await Promise.all(user);
done

2023-02-14 18:22 UTC, rohini-senthil approved these changes

2023-02-14 18:22 UTC, merged