Feat : update case Study endpoints
tech-university-india/staffing-pipeline-backend pull request #23
Opened 2023-02-11 12:55 UTC by rishusingh022

2023-02-12 04:47 UTC, rohini-senthil commented on src/controllers/case-study.controller.js
> +    if (!updatedCaseStudy) return res.status(404).json({ message: 'CaseStudy not found' });
Can we change the error message to "Case study not found"

2023-02-12 04:48 UTC, rohini-senthil commented on src/routes/user.route.js
>  router.put('/users/:id', updateIdValidator, updateBodyValidator, userControllers.updateUser);
Can we add auth to this route?

2023-02-12 04:48 UTC, rohini-senthil commented on src/routes/case-study.route.js
> +router.put('/:id', updateCaseStudyIdValidator, updateCaseStudyBodyValidator, updateCaseStudyController);
Can we add auth to this route?

2023-02-12 04:53 UTC, rohini-senthil commented on src/middlewares/case-study.update.validator.js
> +const Joi = require('joi');
Can we have all case study validators in the same file as `case-study.validator.js`, same for user as well

2023-02-12 06:01 UTC, rishusingh022 commented on src/controllers/case-study.controller.js
> +    if (!updatedCaseStudy) return res.status(404).json({ message: 'CaseStudy not found' });
sure !

2023-02-12 06:01 UTC, rishusingh022 commented on src/middlewares/case-study.update.validator.js
> +const Joi = require('joi');
done

2023-02-12 06:01 UTC, rishusingh022 commented on src/routes/case-study.route.js
> +router.put('/:id', updateCaseStudyIdValidator, updateCaseStudyBodyValidator, updateCaseStudyController);
done

2023-02-12 06:01 UTC, rishusingh022 commented on src/routes/user.route.js
>  router.put('/users/:id', updateIdValidator, updateBodyValidator, userControllers.updateUser);
done

2023-02-12 09:25 UTC, Chetan-MckinseyBEBR reviewed
Added few comments

2023-02-12 09:25 UTC, Chetan-MckinseyBEBR commented on src/controllers/case-study.controller.js
> +const updateCaseStudyServices = require('../services/case-study.service');
Rename updateCaseStudyServices to updateCaseStudy. No need to specify service as part of variable name

2023-02-12 09:25 UTC, Chetan-MckinseyBEBR commented on src/middlewares/case-study.validator.js
> +  updateCaseStudyIdValidator,
Why separate Validators? one for ID and one for body?

2023-02-12 09:25 UTC, Chetan-MckinseyBEBR commented on src/routes/case-study.route.js
> +  updateCaseStudyBodyValidator,
Can't we have a single validator?

2023-02-12 10:30 UTC, rohini-senthil commented on tests/controllers/case-study.controller.test.js
> +      const mockRes = {
Can we move all our mocks to a separate file under `tests/mocks` so it doesn't crowd the file

2023-02-12 10:30 UTC, rohini-senthil requested changes
Requested changes

2023-02-12 12:14 UTC, rishusingh022 commented on src/middlewares/case-study.validator.js
> +  updateCaseStudyIdValidator,
they are separate because in delete we can use the same id validator to validator the id

2023-02-12 12:15 UTC, rishusingh022 commented on src/middlewares/case-study.validator.js
> +  updateCaseStudyIdValidator,
i have done that refactoring part in delete case study 
both the thing

2023-02-12 12:15 UTC, rishusingh022 commented on tests/controllers/case-study.controller.test.js
> +      const mockRes = {
sure !!

2023-02-12 12:16 UTC, rishusingh022 commented on tests/controllers/case-study.controller.test.js
> +      const mockRes = {
creating that mock thing in the delete case study as it already has both things !!

2023-02-14 04:33 UTC, rohini-senthil commented on src/services/case-study.service.js
> +  const updatedCaseStudy = await case_studies.findOne({ where: { case_study_id: id } });
This variable should be `caseStudy` since it's not updated yet

2023-02-14 04:35 UTC, rohini-senthil commented on src/services/case-study.service.js
> +  const updatedCaseStudy = await case_studies.findOne({ where: { case_study_id: id } });
You can change the input name to something like `body`

2023-02-14 15:34 UTC, rohini-senthil approved these changes

2023-02-14 15:34 UTC, merged