Feat : add delete caseStudies endpoint
tech-university-india/staffing-pipeline-backend pull request #24
Opened 2023-02-11 20:50 UTC by rishusingh022

2023-02-12 04:52 UTC, rohini-senthil commented on src/middlewares/case-study.delete.validator.js
> +const Joi = require('joi');
Can we have all case study validators in the same file as `case-study.validator.js`, same for user as well

2023-02-12 06:55 UTC, rishusingh022 commented on src/middlewares/case-study.delete.validator.js
> +const Joi = require('joi');
done !!

2023-02-12 10:31 UTC, rohini-senthil commented on src/controllers/case-study.controller.js
> +const updateCaseStudyServices = require('../services/case-study.service');
Can we keep this `caseStudyService`? It is not solely related only to update case study

2023-02-12 10:33 UTC, rohini-senthil commented on src/middlewares/case-study.validator.js
> +const CaseStudyIdValidator = (req, res, next) => {
`CaseStudyIdValidator ` – This shouldn't be capitalized

2023-02-12 10:33 UTC, rohini-senthil requested changes
Requested changes

2023-02-12 11:42 UTC, rishusingh022 commented on src/middlewares/case-study.validator.js
> +const CaseStudyIdValidator = (req, res, next) => {
done !

2023-02-12 11:42 UTC, rishusingh022 commented on src/controllers/case-study.controller.js
> +const updateCaseStudyServices = require('../services/case-study.service');
done !!

2023-02-14 17:24 UTC, rohini-senthil commented on src/controllers/case-study.controller.js
> +const deleteCaseStudyController = async (req, res) => {
This doesn't need to be named "Controller" explicitly. Let's rename these methods to `updateCaseStudy` and `deleteCaseStudy`

2023-02-14 17:33 UTC, rohini-senthil commented on src/middlewares/case-study.validator.js
> +const CaseStudyIdSchema = Joi.object({
Can we change this to camel case?

2023-02-14 17:38 UTC, merged