Project/update project
tech-university-india/staffing-pipeline-backend pull request #26
Opened 2023-02-12 07:17 UTC by khushilms-cs19

2023-02-12 09:57 UTC, Chetan-MckinseyBEBR approved these changes

2023-02-12 10:02 UTC, rohini-senthil commented on database/config/config.json
> +    "database": "postgres",
Can we agree with the team on which db name we want to keep here and stick with that?

2023-02-12 10:11 UTC, rohini-senthil requested changes

2023-02-12 10:11 UTC, rohini-senthil commented on src/services/project.service.js
> +          }
All direct user table/db interactions should reside in user.service and that method should be imported and called here

2023-02-12 14:06 UTC, khushilms-cs19 commented on database/config/config.json
> +    "database": "postgres",
Yes will discuss with the team and finalise on that.

2023-02-12 14:07 UTC, khushilms-cs19 commented on src/services/project.service.js
> +          }
Okay will make the changes and push

2023-02-14 04:13 UTC, rohini-senthil commented on src/services/project.service.js
> +const HttpError = require('../utils/httpError');
I think the file name is `../utils/HttpError` in main, let's rename that to `../utils/httpError` as well as change the imported variable to camel case (`httpError`)

2023-02-14 04:17 UTC, rohini-senthil commented on src/services/project.service.js
> +  }
We are passing the updated list of userIds, we can directly update.

i.e, if project initially has userIds [1, 2, 3], then your request coming in will contain the final list ex: [1, 3, 4] – so you can directly update the project userIds field to the incoming body field of the same

2023-02-14 04:20 UTC, rohini-senthil commented on src/services/project.service.js
> +  }
Hence, a simple `engagement[key] = body[key];` would suffice here

2023-02-14 04:38 UTC, rohini-senthil commented on src/services/project.service.js
> +      //remove engagementId from all users not in body
Let's move service functions from different entities (user) to the level above (controller) so the project  service file is not internally dependent and is modular

2023-02-16 16:14 UTC, rohini-senthil commented on tests/services/project.service.test.js
> +      name: 'Test Project',
Can we move this mocks folder?

2023-02-16 16:17 UTC, rohini-senthil commented on src/controllers/project.controller.js
> +    const updatedProject = await projectServices.updateProject(id, body);
Can we call `removeCurrentEngagement` and `addCurrentEngagement` from the controller? Once a project is updated, we iterate over body.userIds if present  and update the user with the functions mentioned

2023-02-16 16:20 UTC, rohini-senthil commented on src/services/project.service.js
> +      //remove engagementId from all users not in body
Let's remove this comment

2023-02-16 16:29 UTC, khushilms-cs19 commented on src/services/project.service.js
> +      //remove engagementId from all users not in body
yes will do, i had kept it for my reference and understanding.

2023-02-16 18:04 UTC, khushilms-cs19 commented on src/controllers/project.controller.js
> +    const updatedProject = await projectServices.updateProject(id, body);
I transfered the services to the controllers

2023-02-16 19:46 UTC, rohini-senthil commented on src/services/user.service.js
> +const getUserByPk = async userId => {
This is the same as `getUser` service function since there'll only be one user for each userId, let's use that method instead

2023-02-16 19:49 UTC, rohini-senthil commented on src/controllers/project.controller.js
> +    const { body } = req;
The logger module is added by @Promit-revar. Let's add logs for the controller and service functions and remove console.log()

2023-02-18 08:29 UTC, khushilms-cs19 commented on src/controllers/project.controller.js
> +    const { body } = req;
i have added the logger.

2023-02-18 08:33 UTC, khushilms-cs19 commented on src/services/user.service.js
> +const getUserByPk = async userId => {
I have replaced the function `getUserByPk` with `getUser`  in all occurrences.

2023-02-19 09:56 UTC, rohini-senthil approved these changes

2023-02-19 09:56 UTC, merged