feat: add  upload excel functionality and storing excel data in the Database
tech-university-india/staffing-pipeline-backend pull request #60
Opened 2023-03-16 07:36 UTC by Promit-revar

2023-03-17 10:08 UTC, Chetan-MckinseyBEBR requested changes
Added few comments

2023-03-17 10:08 UTC, Chetan-MckinseyBEBR commented on database/config/config.json
> +    "database": "staffing_pipeline_DB",
DB name??

2023-03-17 10:08 UTC, Chetan-MckinseyBEBR commented on src/controllers/upload-excel.controller.js
> +  console.log(req.file);
consoles shouldn't be there in code

2023-03-18 14:55 UTC, Sukhacoder02 approved these changes

2023-03-19 11:29 UTC, Chetan-MckinseyBEBR approved these changes

2023-03-19 11:29 UTC, merged